import type { ActivityItem, CalendarEvent, CommunicationChannel, CommunicationDirection, CommunicationEvent, CommunicationStatus, Lead, WorkspaceSnapshot } from '../domain/types'
import { env } from '../lib/env'
import { createUuid } from '../lib/id'
import { getSupabaseClient } from '../lib/supabase'
import { safeStorage } from '../lib/storage'
import { enqueueIntegrationSync, loadIntegrationFramework, type ConnectedAccount } from './integration-framework'

export interface EmailAttachmentDraft { id:string; fileName:string; contentType:string; sizeBytes:number; base64:string; disposition:'attachment'|'inline'; contentId?:string }
export interface CommunicationDraft {
  workspaceId: string; leadId: string; accountId: string | null; channel: 'email' | 'whatsapp'; recipient: string
  cc?: string[]; bcc?: string[]; subject: string; body: string; bodyHtml?: string; templateId?: string | null
  replyToExternalMessageId?: string | null; attachments?: EmailAttachmentDraft[]; idempotencyKey?: string
}
export interface EmailTemplateRecord { id:string; workspaceId:string; name:string; category:string; subjectTemplate:string; bodyHtmlTemplate:string; bodyTextTemplate:string; shared:boolean; active:boolean; createdAt:string; updatedAt:string }
export interface CommunicationSubscription { id:string; workspaceId:string; accountId:string; provider:'google'|'microsoft'; resourceType:string; status:string; cursor:string|null; cursorKind:string|null; expirationAt:string|null; renewAfter:string|null; lastNotificationAt:string|null; lastRenewedAt:string|null; lastError:string|null; metadata:Record<string,unknown> }
export interface IntegrationSyncConflict { id:string; workspaceId:string; accountId:string; provider:'google'|'microsoft'; resourceType:string; localResourceId:string|null; externalResourceId:string|null; status:string; resolution:string|null; localSnapshot:Record<string,unknown>; externalSnapshot:Record<string,unknown>; detectedAt:string; resolvedAt:string|null }
export interface UnifiedTimelineEntry { id:string; leadId:string|null; channel:CommunicationChannel; direction:CommunicationDirection; status:CommunicationStatus|'completed'|'pending'; date:string; title:string; description:string; detail:string; source:'communication'|'activity'|'call'|'calendar' }

const STORAGE_PREFIX='realtalent-v10046-communications:'
const TEMPLATE_PREFIX='realtalent-v10046-email-templates:'
const DEFAULT_PREFIX='realtalent-v10046-account-default:'
const storageKey=(workspaceId:string)=>`${STORAGE_PREFIX}${workspaceId}`
const now=()=>new Date().toISOString()
const table=(client:unknown,name:string)=>(client as {from(name:string):any}).from(name)
const objectValue=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}
const stripHtml=(value:string)=>value.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()
const sanitizeHtml=(value:string)=>value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/\son\w+\s*=\s*(['"]).*?\1/gi,'').replace(/javascript:/gi,'')
const readLocal=(workspaceId:string):CommunicationEvent[]=>{const raw=safeStorage.getItem(storageKey(workspaceId));if(!raw)return[];try{const parsed=JSON.parse(raw) as unknown;return Array.isArray(parsed)?parsed as CommunicationEvent[]:[]}catch{return[]}}
const writeLocal=(workspaceId:string,events:CommunicationEvent[])=>safeStorage.setItem(storageKey(workspaceId),JSON.stringify(events.slice(0,1000)))
const seedTemplates=(workspaceId:string):EmailTemplateRecord[]=>[
  {id:'template-followup',workspaceId,name:'Follow-up comercial',category:'Prospecção',subjectTemplate:'Retomando nossa conversa, {{nome}}',bodyHtmlTemplate:'<p>Olá, <strong>{{nome}}</strong>.</p><p>Estou retomando nossa conversa sobre como a {{empresa}} pode avançar com a próxima etapa.</p><p>Podemos alinhar isso nesta semana?</p>',bodyTextTemplate:'Olá, {{nome}}.\n\nEstou retomando nossa conversa sobre como a {{empresa}} pode avançar com a próxima etapa.\n\nPodemos alinhar isso nesta semana?',shared:true,active:true,createdAt:now(),updatedAt:now()},
  {id:'template-proposal',workspaceId,name:'Envio de proposta',category:'Propostas',subjectTemplate:'Proposta comercial · {{empresa}}',bodyHtmlTemplate:'<p>Olá, <strong>{{nome}}</strong>.</p><p>Conforme alinhado, seguem os detalhes da proposta preparada para a {{empresa}}.</p><p>Fico à disposição para revisar qualquer ponto.</p>',bodyTextTemplate:'Olá, {{nome}}.\n\nConforme alinhado, seguem os detalhes da proposta preparada para a {{empresa}}.\n\nFico à disposição para revisar qualquer ponto.',shared:true,active:true,createdAt:now(),updatedAt:now()},
]

export function renderTemplateVariables(value:string,variables:Record<string,string>){return value.replace(/{{\s*([\w.-]+)\s*}}/g,(_,key:string)=>variables[key]??'')}
export function validateEmailAttachments(files:EmailAttachmentDraft[]){if(files.length>10)throw new Error('Selecione no máximo 10 anexos.');let total=0;for(const file of files){if(file.sizeBytes>5*1024*1024)throw new Error(`${file.fileName} ultrapassa 5 MB.`);total+=file.sizeBytes}if(total>10*1024*1024)throw new Error('O total dos anexos ultrapassa 10 MB.');return total}

export async function loadCommunicationEvents(workspaceId:string,leadId?:string|null):Promise<CommunicationEvent[]>{
  const client=getSupabaseClient();if(!client)return readLocal(workspaceId).filter((item)=>!leadId||item.leadId===leadId)
  let query=table(client,'communication_events').select('*').eq('organization_id',workspaceId).order('occurred_at',{ascending:false}).limit(500);if(leadId)query=query.eq('lead_id',leadId)
  const {data,error}=await query;if(error)return readLocal(workspaceId).filter((item)=>!leadId||item.leadId===leadId)
  const events=(data??[]).map((row:any):CommunicationEvent=>({id:row.id,workspaceId:row.organization_id,leadId:row.lead_id,accountId:row.account_id,threadId:row.thread_id,channel:row.channel,direction:row.direction,eventType:row.event_type,status:row.status,externalMessageId:row.external_message_id,internetMessageId:row.internet_message_id??null,replyToExternalMessageId:row.reply_to_external_message_id??null,senderAddress:row.sender_address||'',recipientAddresses:Array.isArray(row.recipient_addresses)?row.recipient_addresses:[],subject:row.subject||'',bodyText:row.body_text||'',bodyHtml:row.body_html||'',hasAttachments:Boolean(row.has_attachments),occurredAt:row.occurred_at,metadata:objectValue(row.metadata),createdAt:row.created_at}))
  writeLocal(workspaceId,events);return events
}

export async function loadEmailTemplates(workspaceId:string):Promise<EmailTemplateRecord[]>{
  const client=getSupabaseClient();if(!client){const raw=safeStorage.getItem(`${TEMPLATE_PREFIX}${workspaceId}`);if(raw){try{return JSON.parse(raw) as EmailTemplateRecord[]}catch{}}const seeded=seedTemplates(workspaceId);safeStorage.setItem(`${TEMPLATE_PREFIX}${workspaceId}`,JSON.stringify(seeded));return seeded}
  const {data,error}=await table(client,'email_templates').select('*').eq('organization_id',workspaceId).eq('active',true).order('category').order('name');if(error)return seedTemplates(workspaceId)
  return (data??[]).map((row:any)=>({id:row.id,workspaceId:row.organization_id,name:row.name,category:row.category,subjectTemplate:row.subject_template||'',bodyHtmlTemplate:row.body_html_template||'',bodyTextTemplate:row.body_text_template||'',shared:Boolean(row.shared),active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at}))
}
export async function saveEmailTemplate(workspaceId:string,input:Omit<EmailTemplateRecord,'id'|'workspaceId'|'active'|'createdAt'|'updatedAt'>){
  const client=getSupabaseClient();const record:EmailTemplateRecord={id:createUuid(),workspaceId,...input,active:true,createdAt:now(),updatedAt:now()};if(!client){const current=await loadEmailTemplates(workspaceId);safeStorage.setItem(`${TEMPLATE_PREFIX}${workspaceId}`,JSON.stringify([record,...current.filter((item)=>item.name!==record.name)]));return record}
  const {data,error}=await table(client,'email_templates').upsert({organization_id:workspaceId,name:input.name,category:input.category,subject_template:input.subjectTemplate,body_html_template:sanitizeHtml(input.bodyHtmlTemplate),body_text_template:input.bodyTextTemplate,shared:input.shared,active:true},{onConflict:'organization_id,name'}).select('*').single();if(error)throw new Error(`Não foi possível salvar o template: ${error.message}`)
  return {id:data.id,workspaceId:data.organization_id,name:data.name,category:data.category,subjectTemplate:data.subject_template||'',bodyHtmlTemplate:data.body_html_template||'',bodyTextTemplate:data.body_text_template||'',shared:Boolean(data.shared),active:Boolean(data.active),createdAt:data.created_at,updatedAt:data.updated_at}
}

export async function loadCommunicationSubscriptions(workspaceId:string):Promise<CommunicationSubscription[]>{const client=getSupabaseClient();if(!client)return[];const {data,error}=await table(client,'communication_subscriptions').select('*').eq('organization_id',workspaceId).order('resource_type');if(error)return[];return(data??[]).map((row:any)=>({id:row.id,workspaceId:row.organization_id,accountId:row.account_id,provider:row.resource_type==='google_calendar'?'google':'microsoft',resourceType:row.resource_type,status:row.status,cursor:row.sync_cursor??null,cursorKind:row.cursor_kind??null,expirationAt:row.expiration_at??null,renewAfter:row.renew_after??null,lastNotificationAt:row.last_notification_at??null,lastRenewedAt:row.last_renewed_at??null,lastError:row.last_error??null,metadata:objectValue(row.metadata)}))}
export async function loadIntegrationConflicts(workspaceId:string):Promise<IntegrationSyncConflict[]>{const client=getSupabaseClient();if(!client)return[];const {data,error}=await table(client,'integration_sync_conflicts').select('*').eq('organization_id',workspaceId).eq('status','open').order('detected_at',{ascending:false}).limit(100);if(error)return[];return(data??[]).map((row:any)=>({id:row.id,workspaceId:row.organization_id,accountId:row.account_id,provider:row.resource_type==='google_calendar'?'google':'microsoft',resourceType:row.resource_type,localResourceId:row.local_resource_id,externalResourceId:row.external_resource_id,status:row.status,resolution:row.resolution,localSnapshot:objectValue(row.local_snapshot),externalSnapshot:objectValue(row.external_snapshot),detectedAt:row.detected_at,resolvedAt:row.resolved_at}))}
export async function resolveIntegrationConflict(workspaceId:string,conflictId:string,resolution:'keep_local'|'keep_external'|'ignore'){const client=getSupabaseClient();if(!client)return true;const {data,error}=await client.rpc('resolve_integration_sync_conflict',{p_conflict_id:conflictId,p_resolution:resolution});if(error)throw new Error(`Não foi possível resolver o conflito: ${error.message}`);return Boolean(data)}

export async function resolveDefaultIntegrationAccount(workspaceId:string,capability:'email_send'|'mail_sync'|'calendar_sync'|'calendar_write'){const client=getSupabaseClient();if(!client)return safeStorage.getItem(`${DEFAULT_PREFIX}${workspaceId}:${capability}`);const {data,error}=await client.rpc('resolve_default_integration_account',{p_organization_id:workspaceId,p_capability:capability});if(error)return null;return typeof data==='string'?data:null}
export async function setDefaultIntegrationAccount(workspaceId:string,capability:'email_send'|'mail_sync'|'calendar_sync'|'calendar_write',accountId:string,scope:'personal'|'organization'='personal'){const client=getSupabaseClient();if(!client){safeStorage.setItem(`${DEFAULT_PREFIX}${workspaceId}:${capability}`,accountId);return accountId}const {data,error}=await client.rpc('set_default_integration_account',{p_organization_id:workspaceId,p_capability:capability,p_account_id:accountId,p_scope:scope});if(error)throw new Error(`Não foi possível definir a conta padrão: ${error.message}`);return String(data)}

export async function sendOfficialCommunication(input:CommunicationDraft):Promise<CommunicationEvent>{
  validateEmailAttachments(input.attachments??[]);const client=getSupabaseClient()
  if(!client||!env.supabaseUrl){const event:CommunicationEvent={id:createUuid(),workspaceId:input.workspaceId,leadId:input.leadId,accountId:input.accountId,threadId:null,channel:input.channel,direction:'outbound',eventType:input.channel==='email'?'email':'message',status:'queued',externalMessageId:null,internetMessageId:null,replyToExternalMessageId:input.replyToExternalMessageId??null,senderAddress:'modo-local',recipientAddresses:[input.recipient,...(input.cc??[]),...(input.bcc??[])],subject:input.subject.trim(),bodyText:input.body.trim(),bodyHtml:sanitizeHtml(input.bodyHtml??''),hasAttachments:Boolean(input.attachments?.length),occurredAt:now(),metadata:{simulated:true,idempotencyKey:input.idempotencyKey||createUuid(),templateId:input.templateId??null,attachmentCount:input.attachments?.length??0},createdAt:now()};const current=readLocal(input.workspaceId);writeLocal(input.workspaceId,[event,...current]);return event}
  const {data:sessionData}=await client.auth.getSession();const token=sessionData.session?.access_token;if(!token)throw new Error('Sua sessão expirou. Entre novamente antes de enviar.')
  const response=await fetch(`${env.supabaseUrl.replace(/\/$/,'')}/functions/v1/official-communication-send`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({organizationId:input.workspaceId,leadId:input.leadId,accountId:input.accountId,channel:input.channel,recipient:input.recipient,cc:input.cc??[],bcc:input.bcc??[],subject:input.subject,body:input.body,bodyHtml:sanitizeHtml(input.bodyHtml??''),templateId:input.templateId??null,replyToExternalMessageId:input.replyToExternalMessageId??null,attachments:input.attachments??[],idempotencyKey:input.idempotencyKey||`${input.channel}:${input.leadId}:${Date.now()}`})})
  const payload=await response.json().catch(()=>({})) as {event?:CommunicationEvent;error?:string};if(!response.ok||!payload.event)throw new Error(payload.error||'Não foi possível colocar a comunicação na fila.');return payload.event
}

const activityTitle:Record<ActivityItem['type'],string>={call:'Ligação programada',followup:'Follow-up',meeting:'Reunião',note:'Nota',stage_change:'Mudança de etapa',email:'E-mail',whatsapp:'WhatsApp'}
export function buildUnifiedTimeline(snapshot:WorkspaceSnapshot,communicationEvents:CommunicationEvent[],leadId?:string|null):UnifiedTimelineEntry[]{const allow=(candidate:string|null)=>!leadId||candidate===leadId;const activities=snapshot.activities.filter((item)=>allow(item.leadId)).map((item):UnifiedTimelineEntry=>({id:`activity-${item.id}`,leadId:item.leadId,channel:item.type==='email'?'email':item.type==='whatsapp'?'whatsapp':item.type==='meeting'?'meeting':item.type==='call'?'call':'note',direction:'internal',status:item.completedAt?'completed':'pending',date:item.completedAt??item.dueAt??item.createdAt,title:activityTitle[item.type],description:item.title,detail:item.description||(item.completedAt?'Concluída':'Pendente'),source:'activity'}));const calls=snapshot.calls.filter((item)=>allow(item.leadId)).map((item):UnifiedTimelineEntry=>({id:`call-${item.id}`,leadId:item.leadId,channel:'call',direction:'outbound',status:'completed',date:item.endedAt??item.startedAt,title:'Ligação registrada',description:item.notes||'Ligação registrada sem observações.',detail:`${Math.max(0,Math.round(item.durationSeconds/60))} min · ${item.outcome.replaceAll('_',' ')}`,source:'call'}));const calendar=snapshot.events.filter((item)=>allow(item.leadId)).map((item):UnifiedTimelineEntry=>({id:`calendar-${item.id}`,leadId:item.leadId,channel:'calendar',direction:'internal',status:item.status==='cancelled'?'cancelled':item.status==='completed'?'completed':'pending',date:item.startsAt,title:item.title,description:item.description||item.location||'Evento comercial',detail:`${item.status} · agenda`,source:'calendar'}));const external=communicationEvents.filter((item)=>allow(item.leadId)).map((item):UnifiedTimelineEntry=>({id:`communication-${item.id}`,leadId:item.leadId,channel:item.channel,direction:item.direction,status:item.status,date:item.occurredAt,title:item.subject||(item.channel==='whatsapp'?'Mensagem no WhatsApp':item.channel==='email'?'E-mail':'Comunicação'),description:item.bodyText||stripHtml(item.bodyHtml)||'Evento recebido do canal oficial.',detail:`${item.direction==='inbound'?'Recebida':item.direction==='outbound'?'Enviada':'Interna'} · ${item.status}${item.hasAttachments?' · com anexos':''}`,source:'communication'}));return[...external,...calls,...calendar,...activities].filter((item)=>item.date).sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime())}
export function leadForCommunication(leads:Lead[],event:CommunicationEvent){return event.leadId?leads.find((lead)=>lead.id===event.leadId)??null:null}
export const communicationChannelLabel:Record<CommunicationChannel,string>={email:'E-mail',whatsapp:'WhatsApp',calendar:'Calendário',call:'Ligação',meeting:'Reunião',note:'Nota',system:'Sistema'}

export async function queueCalendarMutation(workspaceId:string,eventId:string,mutation:'create'|'update'|'delete',event?:CalendarEvent|null){const framework=await loadIntegrationFramework(workspaceId);const defaultId=await resolveDefaultIntegrationAccount(workspaceId,'calendar_write');const account=framework.accounts.find((item)=>item.id===defaultId&&item.status==='connected')??framework.accounts.find((item)=>item.status==='connected'&&['google','microsoft'].includes(item.provider));if(!account)return null;let externalEventId:string|null=null;const client=getSupabaseClient();if(client){const{data}=await table(client,'calendar_external_links').select('external_event_id').eq('organization_id',workspaceId).eq('event_id',eventId).eq('account_id',account.id).maybeSingle();externalEventId=data?.external_event_id??null}return enqueueIntegrationSync(workspaceId,account,account.provider==='google'?'google_calendar_push':'microsoft_calendar_push',{eventId,mutation,event:event??null,externalEventId})}

export function compatibleEmailAccounts(accounts:ConnectedAccount[]){return accounts.filter((item)=>item.status==='connected'&&['google','microsoft'].includes(item.provider))}
