import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, Code2, Eye, FileText, Inbox, Mail, MessageCircle, Paperclip, RefreshCw, Save, Send, ShieldCheck, Star, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useApp } from '../../app/app-context'
import { Button } from '../../components/ui/button'
import { StatusPill } from '../../components/ui/status-pill'
import { formatDateTime } from '../../domain/formatters'
import type { CommunicationChannel } from '../../domain/types'
import {
  buildUnifiedTimeline, communicationChannelLabel, compatibleEmailAccounts, loadCommunicationEvents, loadCommunicationSubscriptions,
  loadEmailTemplates, loadIntegrationConflicts, renderTemplateVariables, resolveDefaultIntegrationAccount, resolveIntegrationConflict,
  saveEmailTemplate, sendOfficialCommunication, setDefaultIntegrationAccount, validateEmailAttachments,
  type EmailAttachmentDraft, type EmailTemplateRecord, type IntegrationSyncConflict,
} from '../../services/communications'
import { enqueueIntegrationSync, loadIntegrationFramework, providerLabel, type ConnectedAccount } from '../../services/integration-framework'

const iconFor=(channel:CommunicationChannel)=>channel==='email'?Mail:channel==='whatsapp'?MessageCircle:channel==='calendar'||channel==='meeting'?CalendarDays:Clock3
const accountSupports=(account:ConnectedAccount,channel:'email'|'whatsapp')=>channel==='whatsapp'?account.provider==='whatsapp_cloud':['google','microsoft'].includes(account.provider)
const fileToAttachment=(file:File)=>new Promise<EmailAttachmentDraft>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error(`Não foi possível ler ${file.name}.`));reader.onload=()=>{const result=String(reader.result||'');resolve({id:crypto.randomUUID(),fileName:file.name,contentType:file.type||'application/octet-stream',sizeBytes:file.size,base64:result.includes(',')?result.split(',')[1]:result,disposition:'attachment'})};reader.readAsDataURL(file)})
const splitAddresses=(value:string)=>value.split(/[;,\n]+/).map((item)=>item.trim()).filter(Boolean)
const conflictTitle=(conflict:IntegrationSyncConflict)=>String(conflict.externalSnapshot.subject||conflict.externalSnapshot.summary||conflict.localSnapshot.title||'Evento de calendário')

export function CommunicationsPage(){
  const{currentWorkspace,snapshot,canWrite,notify}=useApp()
  const[events,setEvents]=useState<Awaited<ReturnType<typeof loadCommunicationEvents>>>([]);const[accounts,setAccounts]=useState<ConnectedAccount[]>([])
  const[templates,setTemplates]=useState<EmailTemplateRecord[]>([]);const[subscriptions,setSubscriptions]=useState<Awaited<ReturnType<typeof loadCommunicationSubscriptions>>>([]);const[conflicts,setConflicts]=useState<IntegrationSyncConflict[]>([])
  const[channel,setChannel]=useState<'all'|CommunicationChannel>('all');const[direction,setDirection]=useState<'all'|'inbound'|'outbound'>('all');const[search,setSearch]=useState('')
  const[leadId,setLeadId]=useState('');const[composeChannel,setComposeChannel]=useState<'email'|'whatsapp'>('email');const[accountId,setAccountId]=useState('');const[defaultAccountId,setDefaultAccountId]=useState<string|null>(null);const[calendarAccountId,setCalendarAccountId]=useState('');const[calendarDefaultAccountId,setCalendarDefaultAccountId]=useState<string|null>(null)
  const[subject,setSubject]=useState('');const[body,setBody]=useState('');const[bodyHtml,setBodyHtml]=useState('');const[format,setFormat]=useState<'text'|'html'>('html');const[cc,setCc]=useState('');const[bcc,setBcc]=useState('');const[templateId,setTemplateId]=useState('');const[attachments,setAttachments]=useState<EmailAttachmentDraft[]>([])
  const[sending,setSending]=useState(false);const[loading,setLoading]=useState(true);const[showPreview,setShowPreview]=useState(false);const[showTemplateForm,setShowTemplateForm]=useState(false);const[templateName,setTemplateName]=useState('');const[templateCategory,setTemplateCategory]=useState('Geral')

  const refresh=async()=>{if(!currentWorkspace)return;setLoading(true);try{const[nextEvents,framework,nextTemplates,nextSubscriptions,nextConflicts,nextDefault,nextCalendarDefault]=await Promise.all([loadCommunicationEvents(currentWorkspace.id),loadIntegrationFramework(currentWorkspace.id),loadEmailTemplates(currentWorkspace.id),loadCommunicationSubscriptions(currentWorkspace.id),loadIntegrationConflicts(currentWorkspace.id),resolveDefaultIntegrationAccount(currentWorkspace.id,'email_send'),resolveDefaultIntegrationAccount(currentWorkspace.id,'calendar_write')]);const connected=framework.accounts.filter((item)=>item.status==='connected');setEvents(nextEvents);setAccounts(connected);setTemplates(nextTemplates);setSubscriptions(nextSubscriptions);setConflicts(nextConflicts);setDefaultAccountId(nextDefault);setCalendarDefaultAccountId(nextCalendarDefault);setCalendarAccountId(nextCalendarDefault??connected.find((item)=>['google','microsoft'].includes(item.provider))?.id??'')}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[currentWorkspace?.id])
  const timeline=useMemo(()=>snapshot?buildUnifiedTimeline(snapshot,events):[],[snapshot,events]);const filtered=useMemo(()=>timeline.filter((item)=>{if(channel!=='all'&&item.channel!==channel)return false;if(direction!=='all'&&item.direction!==direction)return false;const lead=snapshot?.leads.find((candidate)=>candidate.id===item.leadId);const query=`${item.title} ${item.description} ${lead?.name??''} ${lead?.company??''}`.toLocaleLowerCase('pt-BR');return!search.trim()||query.includes(search.trim().toLocaleLowerCase('pt-BR'))}),[timeline,channel,direction,search,snapshot])
  const selectedLead=snapshot?.leads.find((item)=>item.id===leadId)??null;const compatibleAccounts=composeChannel==='email'?compatibleEmailAccounts(accounts):accounts.filter((item)=>accountSupports(item,composeChannel))
  useEffect(()=>{if(!compatibleAccounts.some((item)=>item.id===accountId)){const preferred=compatibleAccounts.find((item)=>item.id===defaultAccountId);setAccountId(preferred?.id??compatibleAccounts[0]?.id??'')}},[composeChannel,accounts,defaultAccountId])
  const variables=useMemo(()=>({nome:selectedLead?.name??'',empresa:selectedLead?.company??'',email:selectedLead?.email??'',telefone:selectedLead?.phone??'',cidade:selectedLead?.city??''}),[selectedLead])
  const previewHtml=useMemo(()=>format==='html'?(bodyHtml||'<p>Escreva o conteúdo HTML para visualizar.</p>'):`<pre style="white-space:pre-wrap;font-family:Arial,sans-serif">${body.replace(/[&<>]/g,(char)=>char==='&'?'&amp;':char==='<'?'&lt;':'&gt;')}</pre>`,[format,bodyHtml,body])

  const applyTemplate=(nextId:string)=>{setTemplateId(nextId);const template=templates.find((item)=>item.id===nextId);if(!template)return;setSubject(renderTemplateVariables(template.subjectTemplate,variables));setBody(renderTemplateVariables(template.bodyTextTemplate,variables));setBodyHtml(renderTemplateVariables(template.bodyHtmlTemplate,variables));setFormat(template.bodyHtmlTemplate?'html':'text')}
  const attach=async(files:FileList|null)=>{if(!files?.length)return;try{const next=[...attachments,...await Promise.all(Array.from(files).map(fileToAttachment))];validateEmailAttachments(next);setAttachments(next)}catch(error){notify('error',error instanceof Error?error.message:'Anexo inválido.')}}
  const markDefault=async()=>{if(!currentWorkspace||!accountId)return;try{await setDefaultIntegrationAccount(currentWorkspace.id,'email_send',accountId,'personal');setDefaultAccountId(accountId);notify('success','Conta padrão de e-mail atualizada.')}catch(error){notify('error',error instanceof Error?error.message:'Não foi possível definir a conta padrão.')}}
  const markCalendarDefault=async()=>{if(!currentWorkspace||!calendarAccountId)return;try{await setDefaultIntegrationAccount(currentWorkspace.id,'calendar_write',calendarAccountId,'personal');await setDefaultIntegrationAccount(currentWorkspace.id,'calendar_sync',calendarAccountId,'personal');setCalendarDefaultAccountId(calendarAccountId);notify('success','Conta padrão de calendário atualizada.')}catch(error){notify('error',error instanceof Error?error.message:'Não foi possível definir o calendário padrão.')}}
  const saveTemplate=async()=>{if(!currentWorkspace||!templateName.trim())return notify('error','Informe um nome para o template.');try{const saved=await saveEmailTemplate(currentWorkspace.id,{name:templateName.trim(),category:templateCategory.trim()||'Geral',subjectTemplate:subject,bodyHtmlTemplate:bodyHtml,bodyTextTemplate:body,shared:true});setTemplates((current)=>[saved,...current.filter((item)=>item.id!==saved.id&&item.name!==saved.name)]);setTemplateId(saved.id);setShowTemplateForm(false);setTemplateName('');notify('success','Template salvo.')}catch(error){notify('error',error instanceof Error?error.message:'Não foi possível salvar o template.')}}
  const runProviderSync=async(kind:'mail'|'calendar'|'subscription')=>{if(!currentWorkspace)return;const targets=compatibleEmailAccounts;try{for(const account of targets){const jobType=kind==='subscription'?`${account.provider}_subscription_renew`:kind==='mail'?`${account.provider}_mail_pull`:`${account.provider}_calendar_pull`;await enqueueIntegrationSync(currentWorkspace.id,account,jobType,{source:'communications_v10046',manual:true})}notify('success',kind==='subscription'?'Renovação de subscriptions agendada.':'Sincronização agendada.')}catch(error){notify('error',error instanceof Error?error.message:'Falha ao agendar a sincronização.')}}
  const solveConflict=async(conflictId:string,resolution:'keep_local'|'keep_external'|'ignore')=>{if(!currentWorkspace)return;try{await resolveIntegrationConflict(currentWorkspace.id,conflictId,resolution);setConflicts((current)=>current.filter((item)=>item.id!==conflictId));notify('success','Conflito resolvido e registrado.')}catch(error){notify('error',error instanceof Error?error.message:'Não foi possível resolver o conflito.')}}
  const send=async()=>{if(!currentWorkspace||!selectedLead)return notify('error','Selecione um lead.');const recipient=composeChannel==='email'?selectedLead.email:selectedLead.phone.replace(/\D/g,'');if(!recipient)return notify('error',composeChannel==='email'?'O lead não possui e-mail.':'O lead não possui telefone.');if(!body.trim()&&!bodyHtml.trim())return notify('error','Escreva a mensagem antes de enviar.');if(!accountId&&compatibleAccounts.length)return notify('error','Selecione uma conta conectada.');setSending(true);try{const event=await sendOfficialCommunication({workspaceId:currentWorkspace.id,leadId:selectedLead.id,accountId:accountId||null,channel:composeChannel,recipient,cc:splitAddresses(cc),bcc:splitAddresses(bcc),subject,body,bodyHtml:format==='html'?bodyHtml:'',templateId:templateId||null,attachments:composeChannel==='email'?attachments:[]});setEvents((current)=>[event,...current.filter((item)=>item.id!==event.id)]);setBody('');setBodyHtml('');setSubject('');setCc('');setBcc('');setAttachments([]);setTemplateId('');notify('success',event.status==='queued'?'Comunicação colocada na fila oficial.':'Comunicação registrada.')}catch(error){notify('error',error instanceof Error?error.message:'Não foi possível enviar.')}finally{setSending(false)}}

  const inbound=timeline.filter((item)=>item.direction==='inbound').length;const pending=timeline.filter((item)=>['queued','pending','failed'].includes(item.status)).length;const activeSubscriptions=subscriptions.filter((item)=>item.status==='active').length
  return <div className="page-stack communications-page">
    <section className="panel communications-hero"><div><span className="eyebrow"><ShieldCheck size={15}/> V100.46 · Google e Microsoft</span><h2>E-mail e calendários com sincronização contínua</h2><p>Gmail, Outlook, Google Calendar e Microsoft Calendar compartilham timeline, conta padrão, subscriptions e tratamento de conflitos.</p></div><div className="communications-metrics"><span><strong>{timeline.length}</strong> interações</span><span><strong>{inbound}</strong> recebidas</span><span><strong>{pending}</strong> pendentes</span><span><strong>{activeSubscriptions}/{subscriptions.length}</strong> subscriptions</span><Button size="sm" variant="secondary" loading={loading} onClick={()=>void refresh()}><RefreshCw size={15}/> Atualizar</Button></div></section>

    <section className="panel communication-sync-bar"><div><strong>Operação dos provedores</strong><small>Sincronização incremental e renovação podem ser acionadas sem repetir toda a caixa postal.</small><div className="communication-calendar-default"><select aria-label="Conta padrão de calendário" value={calendarAccountId} onChange={(event)=>setCalendarAccountId(event.target.value)}><option value="">Calendário padrão</option>{compatibleEmailAccounts(accounts).map((account)=><option key={account.id} value={account.id}>{account.id===calendarDefaultAccountId?'★ ':''}{account.displayName} · {providerLabel(account.provider)}</option>)}</select><Button size="sm" variant={calendarAccountId===calendarDefaultAccountId?'primary':'secondary'} disabled={!calendarAccountId} onClick={()=>void markCalendarDefault()}><Star size={14}/> Usar na agenda</Button></div></div><div><Button size="sm" variant="secondary" onClick={()=>void runProviderSync('mail')}><Mail size={15}/> Sincronizar e-mails</Button><Button size="sm" variant="secondary" onClick={()=>void runProviderSync('calendar')}><CalendarDays size={15}/> Sincronizar agendas</Button><Button size="sm" variant="secondary" onClick={()=>void runProviderSync('subscription')}><RefreshCw size={15}/> Renovar subscriptions</Button></div></section>

    {conflicts.length?<section className="panel communication-conflicts"><div className="panel__heading"><div><span className="eyebrow"><AlertTriangle size={14}/> Conflitos de calendário</span><h3>Alterações simultâneas precisam de decisão</h3></div><StatusPill tone="warning">{conflicts.length} aberto(s)</StatusPill></div><div className="communication-conflict-list">{conflicts.slice(0,8).map((conflict)=><article key={conflict.id}><div><strong>{conflictTitle(conflict)}</strong><small>{providerLabel(conflict.provider)} · detectado em {formatDateTime(conflict.detectedAt)}</small></div><div><Button size="sm" variant="secondary" onClick={()=>void solveConflict(conflict.id,'keep_local')}>Manter CRM</Button><Button size="sm" variant="secondary" onClick={()=>void solveConflict(conflict.id,'keep_external')}>Usar agenda</Button><Button size="sm" variant="ghost" onClick={()=>void solveConflict(conflict.id,'ignore')}>Ignorar</Button></div></article>)}</div></section>:null}

    <div className="communications-layout"><section className="panel communications-timeline-panel"><div className="panel__heading"><div><span className="eyebrow">Timeline unificada</span><h3>Histórico de todos os canais</h3></div><Inbox size={21}/></div><div className="communications-filters"><input aria-label="Buscar comunicações" placeholder="Buscar lead, empresa ou conteúdo" value={search} onChange={(event)=>setSearch(event.target.value)}/><select value={channel} onChange={(event)=>setChannel(event.target.value as typeof channel)}><option value="all">Todos os canais</option><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option><option value="calendar">Calendário</option><option value="call">Ligações</option><option value="meeting">Reuniões</option><option value="note">Notas</option></select><select value={direction} onChange={(event)=>setDirection(event.target.value as typeof direction)}><option value="all">Entrada e saída</option><option value="inbound">Recebidas</option><option value="outbound">Enviadas</option></select></div>{filtered.length?<div className="communications-timeline">{filtered.slice(0,150).map((entry)=>{const Icon=iconFor(entry.channel);const lead=snapshot?.leads.find((item)=>item.id===entry.leadId);return <article key={entry.id}><span className={`communication-icon communication-icon--${entry.channel}`}><Icon size={16}/></span><div><div className="communication-title"><strong>{entry.title}</strong><StatusPill tone={entry.status==='failed'?'danger':entry.direction==='inbound'?'info':entry.status==='delivered'||entry.status==='read'||entry.status==='completed'?'success':'neutral'}>{entry.detail}</StatusPill></div><p>{entry.description}</p><small>{lead?`${lead.name} · ${lead.company||'Sem empresa'} · `:''}{formatDateTime(entry.date)} · {communicationChannelLabel[entry.channel]}</small></div></article>})}</div>:<div className="communications-empty"><CheckCircle2 size={23}/><strong>Nenhuma comunicação encontrada</strong><span>Conecte uma conta oficial ou registre uma interação comercial.</span></div>}</section>

      <aside className="panel communications-composer"><div className="panel__heading"><div><span className="eyebrow">Nova comunicação</span><h3>Enviar pelo canal oficial</h3></div><Send size={20}/></div><label className="field"><span>Lead</span><select value={leadId} onChange={(event)=>setLeadId(event.target.value)}><option value="">Selecione</option>{snapshot?.leads.filter((item)=>item.status==='active'&&!item.doNotContact).map((item)=><option key={item.id} value={item.id}>{item.name} · {item.company}</option>)}</select></label><div className="communication-channel-switch"><button type="button" className={composeChannel==='email'?'is-active':''} onClick={()=>setComposeChannel('email')}><Mail size={16}/> E-mail</button><button type="button" className={composeChannel==='whatsapp'?'is-active':''} onClick={()=>setComposeChannel('whatsapp')}><MessageCircle size={16}/> WhatsApp</button></div><label className="field"><span>Conta conectada</span><div className="communication-account-row"><select value={accountId} onChange={(event)=>setAccountId(event.target.value)}><option value="">{compatibleAccounts.length?'Selecione':'Modo local / nenhuma conta'}</option>{compatibleAccounts.map((account)=><option key={account.id} value={account.id}>{account.id===defaultAccountId?'★ ':''}{account.displayName} · {providerLabel(account.provider)}</option>)}</select>{composeChannel==='email'&&accountId?<Button type="button" size="sm" variant={accountId===defaultAccountId?'primary':'secondary'} title="Definir como conta padrão" onClick={()=>void markDefault()}><Star size={15}/></Button>:null}</div></label>
      {composeChannel==='email'?<><label className="field"><span>Template</span><div className="communication-template-row"><select value={templateId} onChange={(event)=>applyTemplate(event.target.value)}><option value="">Sem template</option>{templates.map((template)=><option key={template.id} value={template.id}>{template.category} · {template.name}</option>)}</select><Button type="button" size="sm" variant="secondary" onClick={()=>setShowTemplateForm((value)=>!value)}><Save size={15}/></Button></div></label>{showTemplateForm?<div className="communication-template-form"><input placeholder="Nome do template" value={templateName} onChange={(event)=>setTemplateName(event.target.value)}/><input placeholder="Categoria" value={templateCategory} onChange={(event)=>setTemplateCategory(event.target.value)}/><Button type="button" size="sm" onClick={()=>void saveTemplate()}><Save size={14}/> Salvar conteúdo atual</Button></div>:null}<label className="field"><span>Assunto</span><input value={subject} onChange={(event)=>setSubject(event.target.value)} placeholder="Assunto do e-mail"/></label><details className="communication-copy-fields"><summary>Adicionar Cc e Cco</summary><label className="field"><span>Cc</span><input value={cc} onChange={(event)=>setCc(event.target.value)} placeholder="email1@empresa.com; email2@empresa.com"/></label><label className="field"><span>Cco</span><input value={bcc} onChange={(event)=>setBcc(event.target.value)} placeholder="copia.oculta@empresa.com"/></label></details><div className="communication-format-switch"><button type="button" className={format==='text'?'is-active':''} onClick={()=>setFormat('text')}><FileText size={15}/> Texto</button><button type="button" className={format==='html'?'is-active':''} onClick={()=>setFormat('html')}><Code2 size={15}/> HTML</button><button type="button" onClick={()=>setShowPreview((value)=>!value)}><Eye size={15}/> Prévia</button></div></>:null}
      <label className="field"><span>{format==='html'&&composeChannel==='email'?'Versão em texto':'Mensagem'}</span><textarea rows={6} value={body} onChange={(event)=>setBody(event.target.value)} placeholder={selectedLead?`Mensagem para ${selectedLead.name}`:'Selecione um lead'}/></label>{composeChannel==='email'&&format==='html'?<label className="field"><span>Conteúdo HTML</span><textarea className="communication-html-editor" rows={9} value={bodyHtml} onChange={(event)=>setBodyHtml(event.target.value)} placeholder="<p>Olá, <strong>{{nome}}</strong>...</p>"/></label>:null}{showPreview&&composeChannel==='email'?<div className="communication-preview"><iframe title="Prévia do e-mail" sandbox="" srcDoc={previewHtml}/></div>:null}
      {composeChannel==='email'?<div className="communication-attachments"><label><Paperclip size={15}/> Adicionar anexos<input type="file" multiple onChange={(event)=>void attach(event.target.files)}/></label>{attachments.map((file)=><span key={file.id}><Paperclip size={13}/>{file.fileName}<small>{Math.ceil(file.sizeBytes/1024)} KB</small><button type="button" aria-label={`Remover ${file.fileName}`} onClick={()=>setAttachments((current)=>current.filter((item)=>item.id!==file.id))}><X size={13}/></button></span>)}</div>:null}
      <div className="communication-recipient"><small>Destinatário</small><strong>{selectedLead?composeChannel==='email'?selectedLead.email||'E-mail ausente':selectedLead.phone||'Telefone ausente':'Nenhum lead selecionado'}</strong></div><Button disabled={!canWrite||!selectedLead||(!body.trim()&&!bodyHtml.trim())} loading={sending} onClick={()=>void send()}><Send size={16}/> Enviar com auditoria</Button><p className="communication-disclaimer">O envio usa a conta padrão quando nenhuma conta é informada, passa pela fila idempotente e registra HTML, anexos, template e status na timeline.</p></aside></div>

    <section className="panel communication-subscriptions"><div className="panel__heading"><div><span className="eyebrow">Subscriptions e cursores</span><h3>Saúde da sincronização incremental</h3></div><RefreshCw size={20}/></div>{subscriptions.length?<div className="communication-subscription-grid">{subscriptions.map((subscription)=>{const account=accounts.find((item)=>item.id===subscription.accountId);return <article key={subscription.id}><div><strong>{account?.displayName||providerLabel(subscription.provider)}</strong><StatusPill tone={subscription.status==='active'?'success':subscription.status==='renewal_due'?'warning':'danger'}>{subscription.status}</StatusPill></div><span>{subscription.resourceType.replaceAll('_',' ')}</span><small>Cursor: {subscription.cursorKind||'aguardando'} · expira {subscription.expirationAt?formatDateTime(subscription.expirationAt):'sem data'}</small>{subscription.lastError?<small className="text-danger">{subscription.lastError}</small>:null}</article>})}</div>:<div className="communications-empty"><RefreshCw size={22}/><strong>Nenhuma subscription criada</strong><span>Conecte Gmail/Outlook e execute a renovação para ativar notificações.</span></div>}</section>
  </div>
}
