import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}})
const header=(headers:any[],name:string)=>String(headers?.find((item)=>String(item.name).toLowerCase()===name.toLowerCase())?.value||'')
const emailAddress=(value:string)=>{const match=value.match(/<([^>]+)>/);return (match?.[1]||value).trim().toLowerCase()}
const textFromBase64Url=(value:string)=>{try{return decodeURIComponent(escape(atob(value.replaceAll('-','+').replaceAll('_','/'))))}catch{return ''}}
Deno.serve(async(req)=>{
  const expected=Deno.env.get('COMMUNICATION_WORKER_SECRET'); if(!expected||req.headers.get('x-worker-secret')!==expected)return json({error:'Não autorizado'},401)
  const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!) as any
  const encryptionKey=Deno.env.get('INTEGRATION_TOKEN_ENCRYPTION_KEY')||''
  const {data:jobs,error}=await admin.from('integration_sync_jobs').select('*,integration_connected_accounts(*)').in('status',['queued','retry']).in('job_type',['full_sync','gmail_pull','google_calendar_pull','outlook_mail_pull','outlook_calendar_pull','calendar_push']).lte('available_at',new Date().toISOString()).order('priority',{ascending:false}).limit(10)
  if(error)return json({error:error.message},500)
  const results=[]
  for(const job of jobs??[]){
    const attempt=Number(job.attempts||0)+1; const started=Date.now()
    const {data:claimed}=await admin.from('integration_sync_jobs').update({status:'processing',locked_at:new Date().toISOString(),attempts:attempt}).eq('id',job.id).in('status',['queued','retry']).select('id').maybeSingle(); if(!claimed)continue
    try{
      const account=job.integration_connected_accounts; if(!account||account.status!=='connected')throw new Error('Conta não conectada')
      const {data:tokens,error:tokenError}=await admin.rpc('read_integration_oauth_token',{p_account_id:account.id,p_encryption_key:encryptionKey}); if(tokenError||!tokens?.[0]?.access_token)throw new Error(tokenError?.message||'Token indisponível')
      const token=String(tokens[0].access_token); let count=0; const tasks=job.job_type==='full_sync'?(account.provider==='google'?['gmail_pull','google_calendar_pull']:account.provider==='microsoft'?['outlook_mail_pull','outlook_calendar_pull']:[]):[job.job_type]
      for(const task of tasks){
        if(task==='calendar_push'){
          const mutation=String(job.payload?.mutation||'update'); const eventId=String(job.payload?.eventId||''); const externalFromPayload=String(job.payload?.externalEventId||'');
          let event=job.payload?.event||null; if(!event&&eventId){const {data}=await admin.from('calendar_events').select('*').eq('id',eventId).eq('organization_id',account.organization_id).maybeSingle();event=data}
          const {data:link}=eventId?await admin.from('calendar_external_links').select('*').eq('event_id',eventId).eq('account_id',account.id).maybeSingle():{data:null}; const externalId=externalFromPayload||String(link?.external_event_id||'')
          if(mutation==='delete'){
            if(externalId){const endpoint=account.provider==='google'?`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(externalId)}`:`https://graph.microsoft.com/v1.0/me/events/${encodeURIComponent(externalId)}`;const response=await fetch(endpoint,{method:'DELETE',headers:{authorization:`Bearer ${token}`}});if(!response.ok&&response.status!==404)throw new Error('Falha ao excluir evento externo')}
            count++; continue
          }
          if(!event)throw new Error('Evento local não encontrado')
          if(account.provider==='google'){
            const payload={summary:event.title,description:event.description||'',location:event.location||'',start:event.all_day?{date:String(event.starts_at||event.startsAt).slice(0,10)}:{dateTime:event.starts_at||event.startsAt},end:event.all_day?{date:String(event.ends_at||event.endsAt).slice(0,10)}:{dateTime:event.ends_at||event.endsAt}}
            const endpoint=externalId?`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(externalId)}`:'https://www.googleapis.com/calendar/v3/calendars/primary/events';const response=await fetch(endpoint,{method:externalId?'PUT':'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(result?.error?.message||'Falha ao sincronizar Google Calendar');await admin.from('calendar_external_links').upsert({organization_id:account.organization_id,event_id:eventId,account_id:account.id,provider:'google',external_event_id:String(result.id),external_calendar_id:'primary',etag:result.etag||null,last_synced_at:new Date().toISOString()},{onConflict:'event_id,account_id'})
          }else if(account.provider==='microsoft'){
            const payload={subject:event.title,body:{contentType:'Text',content:event.description||''},start:{dateTime:event.starts_at||event.startsAt,timeZone:'UTC'},end:{dateTime:event.ends_at||event.endsAt,timeZone:'UTC'},location:{displayName:event.location||''},isAllDay:Boolean(event.all_day??event.allDay)}
            const endpoint=externalId?`https://graph.microsoft.com/v1.0/me/events/${encodeURIComponent(externalId)}`:'https://graph.microsoft.com/v1.0/me/events';const response=await fetch(endpoint,{method:externalId?'PATCH':'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)});const result=response.status===204?{id:externalId}:await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(result?.error?.message||'Falha ao sincronizar Outlook Calendar');await admin.from('calendar_external_links').upsert({organization_id:account.organization_id,event_id:eventId,account_id:account.id,provider:'microsoft',external_event_id:String(result.id||externalId),external_calendar_id:'default',last_synced_at:new Date().toISOString()},{onConflict:'event_id,account_id'})
          }
          count++; continue
        }
        if(task==='gmail_pull'){
          const listResponse=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=25&q=newer_than:14d',{headers:{authorization:`Bearer ${token}`}}); const list=await listResponse.json().catch(()=>({})) as any; if(!listResponse.ok)throw new Error(list?.error?.message||'Falha ao consultar Gmail')
          for(const item of list.messages||[]){
            const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${item.id}?format=full`,{headers:{authorization:`Bearer ${token}`}}); const message=await response.json().catch(()=>({})) as any; if(!response.ok)continue
            const headers=message.payload?.headers||[]; const from=emailAddress(header(headers,'From')); const to=header(headers,'To').split(',').map(emailAddress).filter(Boolean); const subject=header(headers,'Subject'); const own=String(account.metadata?.email||account.display_name||'').toLowerCase(); const inbound=!own||!from.includes(own)
            let body=message.snippet||''; if(message.payload?.body?.data)body=textFromBase64Url(message.payload.body.data)||body
            if(inbound){await admin.rpc('upsert_inbound_communication',{p_organization_id:account.organization_id,p_account_id:account.id,p_channel:'email',p_external_message_id:String(message.id),p_sender:from,p_recipients:to,p_subject:subject,p_body:body,p_occurred_at:new Date(Number(message.internalDate||Date.now())).toISOString(),p_metadata:{provider:'gmail',thread_id:message.threadId,label_ids:message.labelIds||[]}})}
            else await admin.from('communication_events').upsert({organization_id:account.organization_id,account_id:account.id,channel:'email',direction:'outbound',event_type:'email',status:'sent',external_message_id:String(message.id),sender_address:from,recipient_addresses:to,subject,body_text:body,occurred_at:new Date(Number(message.internalDate||Date.now())).toISOString(),metadata:{provider:'gmail',thread_id:message.threadId}}, {onConflict:'organization_id,channel,external_message_id'})
            count++
          }
        }
        if(task==='outlook_mail_pull'){
          const response=await fetch('https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=25&$select=id,conversationId,subject,bodyPreview,from,toRecipients,receivedDateTime,isRead&$orderby=receivedDateTime desc',{headers:{authorization:`Bearer ${token}`}}); const data=await response.json().catch(()=>({})) as any; if(!response.ok)throw new Error(data?.error?.message||'Falha ao consultar Outlook')
          for(const message of data.value||[]){const from=String(message.from?.emailAddress?.address||'').toLowerCase();const recipients=(message.toRecipients||[]).map((r:any)=>String(r.emailAddress?.address||'')).filter(Boolean);await admin.rpc('upsert_inbound_communication',{p_organization_id:account.organization_id,p_account_id:account.id,p_channel:'email',p_external_message_id:String(message.id),p_sender:from,p_recipients:recipients,p_subject:String(message.subject||''),p_body:String(message.bodyPreview||''),p_occurred_at:String(message.receivedDateTime||new Date().toISOString()),p_metadata:{provider:'outlook',conversation_id:message.conversationId,is_read:message.isRead}});count++}
        }
        if(task==='google_calendar_pull'){
          const timeMin=new Date(Date.now()-30*86400000).toISOString(),timeMax=new Date(Date.now()+180*86400000).toISOString(); const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&maxResults=100&timeMin=${encodeURIComponent(timeMin)}&timeMax=${encodeURIComponent(timeMax)}`,{headers:{authorization:`Bearer ${token}`}}); const data=await response.json().catch(()=>({})) as any; if(!response.ok)throw new Error(data?.error?.message||'Falha ao consultar Google Calendar')
          for(const event of data.items||[]){const starts=event.start?.dateTime||`${event.start?.date}T00:00:00Z`;const ends=event.end?.dateTime||`${event.end?.date}T23:59:59Z`;const {data:link}=await admin.from('calendar_external_links').select('event_id').eq('account_id',account.id).eq('external_event_id',String(event.id)).maybeSingle();let eventId=link?.event_id
            if(eventId)await admin.from('calendar_events').update({title:event.summary||'Evento',description:event.description||'',starts_at:starts,ends_at:ends,all_day:Boolean(event.start?.date),location:event.location||'',status:event.status==='cancelled'?'cancelled':'confirmed',updated_at:new Date().toISOString()}).eq('id',eventId)
            else {const {data:created}=await admin.from('calendar_events').insert({organization_id:account.organization_id,lead_id:null,title:event.summary||'Evento',description:event.description||'',starts_at:starts,ends_at:ends,all_day:Boolean(event.start?.date),location:event.location||'',status:event.status==='cancelled'?'cancelled':'confirmed',assigned_to:account.connected_by_user_id}).select('id').single();eventId=created?.id;if(eventId)await admin.from('calendar_external_links').insert({organization_id:account.organization_id,event_id:eventId,account_id:account.id,provider:'google',external_event_id:String(event.id),external_calendar_id:'primary',etag:event.etag||null})}
            if(eventId)await admin.from('communication_events').upsert({organization_id:account.organization_id,lead_id:null,account_id:account.id,channel:'calendar',direction:'internal',event_type:'calendar_event',status:event.status==='cancelled'?'cancelled':'received',external_message_id:`gcal:${event.id}`,subject:event.summary||'Evento',body_text:event.description||'',occurred_at:starts,metadata:{calendar_event_id:eventId,provider:'google'}},{onConflict:'organization_id,channel,external_message_id'});count++}
        }
        if(task==='outlook_calendar_pull'){
          const start=new Date(Date.now()-30*86400000).toISOString(),end=new Date(Date.now()+180*86400000).toISOString(); const response=await fetch(`https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=${encodeURIComponent(start)}&endDateTime=${encodeURIComponent(end)}&$top=100&$select=id,subject,bodyPreview,start,end,isAllDay,location,isCancelled`,{headers:{authorization:`Bearer ${token}`,'Prefer':'outlook.timezone="UTC"'}}); const data=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(data?.error?.message||'Falha ao consultar Outlook Calendar')
          for(const event of data.value||[]){const starts=String(event.start?.dateTime||start),ends=String(event.end?.dateTime||end);const {data:link}=await admin.from('calendar_external_links').select('event_id').eq('account_id',account.id).eq('external_event_id',String(event.id)).maybeSingle();let eventId=link?.event_id
            if(eventId)await admin.from('calendar_events').update({title:event.subject||'Evento',description:event.bodyPreview||'',starts_at:starts,ends_at:ends,all_day:Boolean(event.isAllDay),location:event.location?.displayName||'',status:event.isCancelled?'cancelled':'confirmed',updated_at:new Date().toISOString()}).eq('id',eventId)
            else {const {data:created}=await admin.from('calendar_events').insert({organization_id:account.organization_id,lead_id:null,title:event.subject||'Evento',description:event.bodyPreview||'',starts_at:starts,ends_at:ends,all_day:Boolean(event.isAllDay),location:event.location?.displayName||'',status:event.isCancelled?'cancelled':'confirmed',assigned_to:account.connected_by_user_id}).select('id').single();eventId=created?.id;if(eventId)await admin.from('calendar_external_links').insert({organization_id:account.organization_id,event_id:eventId,account_id:account.id,provider:'microsoft',external_event_id:String(event.id),external_calendar_id:'default'})}
            if(eventId)await admin.from('communication_events').upsert({organization_id:account.organization_id,lead_id:null,account_id:account.id,channel:'calendar',direction:'internal',event_type:'calendar_event',status:event.isCancelled?'cancelled':'received',external_message_id:`mscal:${event.id}`,subject:event.subject||'Evento',body_text:event.bodyPreview||'',occurred_at:starts,metadata:{calendar_event_id:eventId,provider:'microsoft'}},{onConflict:'organization_id,channel,external_message_id'});count++}
        }
      }
      await admin.from('integration_sync_attempts').insert({organization_id:job.organization_id,job_id:job.id,attempt_number:attempt,status:'succeeded',duration_ms:Date.now()-started})
      await admin.from('integration_sync_jobs').update({status:'succeeded',completed_at:new Date().toISOString(),locked_at:null,last_error:null}).eq('id',job.id)
      await admin.from('integration_connected_accounts').update({last_sync_at:new Date().toISOString(),last_error:null,status:'connected'}).eq('id',account.id);results.push({id:job.id,status:'succeeded',count})
    }catch(error){const message=error instanceof Error?error.message:'Falha desconhecida';const terminal=attempt>=Number(job.max_attempts||5);const delay=Math.min(3600,Math.pow(2,attempt)*60);await admin.from('integration_sync_attempts').insert({organization_id:job.organization_id,job_id:job.id,attempt_number:attempt,status:terminal?'failed':'retry_scheduled',duration_ms:Date.now()-started,error_message:message});await admin.from('integration_sync_jobs').update({status:terminal?'dead_letter':'retry',available_at:new Date(Date.now()+delay*1000).toISOString(),locked_at:null,last_error:message}).eq('id',job.id);await admin.from('integration_connected_accounts').update({status:terminal?'error':'attention',last_error:message}).eq('id',job.account_id);results.push({id:job.id,status:terminal?'dead_letter':'retry',error:message})}
  }
  return json({processed:results.length,results})
})
