import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8')
const checks=[];const check=(id,pass,detail)=>checks.push({id,pass:Boolean(pass),detail})
const migration=read('supabase/migrations/202607280003_v100_46_google_microsoft.sql')
const runtime=read('supabase/functions/_shared/integration-runtime.ts')
const dispatch=read('supabase/functions/communication-dispatch-worker/index.ts')
const maintenance=read('supabase/functions/integration-maintenance-worker/index.ts')
const oauth=read('supabase/functions/integration-oauth-callback/index.ts')
const page=read('src/features/communications/communications-page.tsx')
const service=read('src/services/communications.ts')
const msWebhook=read('supabase/functions/microsoft-communications-webhook/index.ts')
const gmailWebhook=read('supabase/functions/gmail-pubsub-webhook/index.ts')
check('gmail_incremental',runtime.includes('/history?startHistoryId=')&&runtime.includes('gmail_history_id')&&runtime.includes('newer_than:90d'),'Gmail usa historyId e recuperação por sincronização completa.')
check('outlook_delta',runtime.includes("messages/delta")&&runtime.includes("@odata.deltaLink")&&runtime.includes('microsoft_delta_link'),'Outlook usa deltaLink e paginação.')
check('google_calendar_incremental',runtime.includes('syncToken')&&runtime.includes('google_sync_token')&&runtime.includes('response.status === 410'),'Google Calendar usa syncToken com reset controlado.')
check('microsoft_calendar_delta',runtime.includes('calendarView/delta')&&runtime.includes("@odata.nextLink"),'Microsoft Calendar usa delta e paginação.')
check('subscriptions',runtime.includes('/users/me/watch')&&runtime.includes('/events/watch')&&runtime.includes('graph.microsoft.com/v1.0/subscriptions'),'Gmail, Google Calendar e Graph possuem subscriptions reais.')
check('automatic_renewal',maintenance.includes("expectedResources")&&maintenance.includes('subscriptionJobsEnqueued')&&maintenance.includes('renew_after'),'Manutenção renova e-mail e calendário por conta.')
check('oauth_bootstrap',oauth.includes('integration_account_defaults')&&oauth.includes('initial_sync')&&oauth.includes('subscription_renew'),'OAuth cria defaults e inicia sync/subscriptions.')
check('default_account',migration.includes('integration_account_defaults')&&migration.includes('resolve_default_integration_account')&&page.includes('Conta padrão de e-mail atualizada'),'Conta padrão existe no banco e na interface.')
check('timeline',page.includes('Timeline unificada')&&service.includes('buildUnifiedTimeline')&&service.includes('hasAttachments'),'Timeline consolida mensagens e anexos.')
check('conflicts',migration.includes('integration_sync_conflicts')&&runtime.includes('registerCalendarConflict')&&page.includes('Manter CRM')&&page.includes('Usar agenda'),'Conflitos são detectados e resolvidos explicitamente.')
check('html_email',migration.includes('body_html')&&dispatch.includes("contentType:html?'HTML':'Text'")&&dispatch.includes('multipart/alternative'),'HTML é enviado por Gmail e Outlook.')
check('templates',migration.includes('email_templates')&&page.includes('Salvar conteúdo atual')&&service.includes('renderTemplateVariables'),'Templates persistentes e variáveis comerciais estão disponíveis.')
check('attachments',migration.includes('communication_attachments')&&migration.includes('O total de anexos deve ter no máximo 10 MB')&&dispatch.includes('#microsoft.graph.fileAttachment')&&dispatch.includes('multipart/mixed'),'Anexos têm limites, persistência e transporte nos dois provedores.')
check('gmail_pubsub',gmailWebhook.includes('message.data')&&gmailWebhook.includes('history_id')&&gmailWebhook.includes("url.searchParams.get('token')"),'Gmail Pub/Sub valida segredo e enfileira historyId.')
check('microsoft_lifecycle',msWebhook.includes('reauthorizationRequired')&&msWebhook.includes('subscriptionRemoved')&&msWebhook.includes("lifecycleEvent==='missed'"),'Lifecycle do Graph recupera subscription e notificações perdidas.')
check('account_capabilities',migration.includes("'mail_sync',true,'calendar_sync',true")&&oauth.includes('mail_sync:true')&&oauth.includes('calendar_sync:true'),'Capacidades de sincronização são explícitas.')
const failed=checks.filter((item)=>!item.pass);const pkg=JSON.parse(read('package.json'));const label=`V${pkg.version.replace(/\.0$/,'').replaceAll('.','-')}`;const report={version:pkg.version,generatedAt:new Date().toISOString(),checks:checks.length,passed:checks.length-failed.length,failed:failed.length,results:checks};fs.writeFileSync(path.join(root,`GOOGLE-MICROSOFT-AUDIT-${label}.json`),JSON.stringify(report,null,2)+'\n');console.log(`${report.passed}/${report.checks} verificações Google e Microsoft aprovadas.`);if(failed.length){for(const item of failed)console.error(`FALHA ${item.id}: ${item.detail}`);process.exit(1)}
