import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8')
const exists=(relative)=>fs.existsSync(path.join(root,relative))
const checks=[]
const check=(id,pass,detail)=>checks.push({id,pass:Boolean(pass),detail})
const migration=read('supabase/migrations/202607280002_v100_45_integration_foundation.sql')
const service=read('src/services/integration-framework.ts')
const center=read('src/features/settings/integration-center.tsx')
const panel=read('src/features/settings/integration-framework-panel.tsx')
const oauthStart=read('supabase/functions/integration-oauth-start/index.ts')
const oauthCallback=read('supabase/functions/integration-oauth-callback/index.ts')
const deploy=read('scripts/deploy-supabase.mjs')
const config=read('supabase/config.toml')
const runtime=read('supabase/functions/_shared/integration-runtime.ts')
const accountTest=read('supabase/functions/integration-account-test/index.ts')
check('single_ui_source',center.includes('IntegrationFrameworkPanel')&&!center.includes('integration-workspace'),'A central antiga não é renderizada.')
check('legacy_frontend_removed',!exists('src/services/integration-workspace.ts'),'O serviço frontend legado foi removido.')
check('demo_status',service.includes("status:'demo'")&&panel.includes('Modo demonstração identificado'),'Demonstração não aparece como conta conectada.')
check('account_access',migration.includes('update_integration_account_access')&&migration.includes("if v_account.access_mode='personal' then return v_account.connected_by_user_id=auth.uid()")&&!migration.includes("if v_role in ('owner','admin') then return true")&&panel.includes('Modo de acesso'),'Contas pessoais e compartilhadas estão protegidas sem bypass de uso pelo administrador.')
check('account_dml_guard',migration.includes('revoke insert,update,delete on public.integration_connected_accounts from authenticated'),'Alterações de contas conectadas passam somente por RPCs e Edge Functions auditáveis.')
check('pkce',oauthStart.includes('code_challenge_method')&&oauthStart.includes("'S256'")&&oauthCallback.includes('code_verifier'),'PKCE S256 está aplicado.')
check('single_use_state',migration.includes('consume_integration_oauth_state')&&migration.includes('consumed_at=now()')&&oauthCallback.indexOf('consume_integration_oauth_state')<oauthCallback.indexOf('providerError)throw'),'Estado OAuth é persistido e consumido mesmo quando o provedor devolve erro.')
check('token_rotation',exists('supabase/functions/integration-token-worker/index.ts')&&runtime.includes('refreshProviderToken')&&read('supabase/functions/integration-maintenance-worker/index.ts').includes('enqueue_integration_sync_job_system'),'Renovação e rotação de token possuem worker dedicado e enfileiramento service-role.')
for(const name of ['google','microsoft','meta','whatsapp'])check(`worker_${name}`,exists(`supabase/functions/integration-${name}-worker/index.ts`),`Worker ${name} existe.`)
check('generic_workers_retired',read('supabase/functions/integration-sync-worker/index.ts').includes('410')&&read('supabase/functions/communication-sync-worker/index.ts').includes('410'),'Workers genéricos não capturam filas.')
check('allowlist',migration.includes('integration_provider_job_types')&&migration.includes('integration_worker_for_job')&&service.includes('allowedJobTypesForProvider'),'Allowlist existe no banco e no cliente.')
check('lease_recovery',migration.includes('recover_stale_integration_jobs')&&migration.includes('lease_expires_at')&&exists('supabase/functions/integration-maintenance-worker/index.ts'),'Locks expirados são recuperáveis.')
check('complete_secrets',deploy.includes('INTEGRATION_TOKEN_ENCRYPTION_KEY')&&deploy.includes('GMAIL_PUBSUB_WEBHOOK_SECRET')&&deploy.includes("!entry.name.startsWith('_')"),'Deploy valida secrets e ignora _shared.')
check('gateway_contract',config.includes('[functions.integration-oauth-callback]\nverify_jwt = false')&&config.includes('[functions.integration-google-worker]\nverify_jwt = false')&&config.includes('[functions.integration-account-test]\nverify_jwt = true'),'Gateway diferencia callbacks/workers de endpoints autenticados.')
check('diagnostics',exists('supabase/functions/integration-diagnostics/index.ts')&&panel.includes('Executar diagnóstico')&&migration.includes('integration_diagnostics'),'Diagnóstico executável e persistente existe.')
check('connection_test',exists('supabase/functions/integration-account-test/index.ts')&&accountTest.includes('await fetch(endpointFor(account)')&&panel.includes('Testar conexão'),'Teste de conta realiza chamada de rede ao recurso configurado.')
check('provider_revocation',exists('supabase/functions/integration-account-revoke/index.ts')&&service.includes("functions.invoke('integration-account-revoke'")&&read('supabase/functions/integration-account-revoke/index.ts').includes('oauth2.googleapis.com/revoke'),'Revogação remove o cofre e tenta revogar no provedor quando suportado.')
check('signed_whatsapp_webhook',read('supabase/functions/whatsapp-webhook/index.ts').includes('x-hub-signature-256')&&read('supabase/functions/whatsapp-webhook/index.ts').includes('HMAC'),'Webhook do WhatsApp valida assinatura HMAC.')
check('capabilities',panel.includes('Painel de capacidades')&&service.includes('providerCapabilities'),'Capacidades são exibidas por provedor.')
check('real_audit',migration.includes('integration_audit_events')&&panel.includes('Eventos de segurança e operação'),'Auditoria usa eventos operacionais persistidos.')
check('extension_new_source',!read('supabase/functions/extension-ingest/index.ts').includes('integration_connections')&&!read('supabase/functions/extension-ingest/index.ts').includes('integration_events'),'Ingestão da extensão não depende das tabelas legadas.')
const allowlists={google:['google_mail_pull','google_calendar_pull'],microsoft:['microsoft_mail_pull','microsoft_calendar_pull'],meta:['meta_account_sync'],whatsapp_cloud:['whatsapp_account_sync']}
const routed=Object.entries(allowlists).flatMap(([provider,types])=>types.map(type=>({provider,type,worker:type.startsWith('google_')?'google-sync':type.startsWith('microsoft_')?'microsoft-sync':type.startsWith('meta_')?'meta-sync':type.startsWith('whatsapp_')?'whatsapp-sync':'invalid'})))
check('allowlist_simulation',routed.every(item=>item.worker===`${item.provider==='whatsapp_cloud'?'whatsapp':item.provider}-sync`)&&new Set(routed.map(item=>`${item.worker}:${item.type}`)).size===routed.length,'Simulação executável de roteamento não cruza provedores.')
const failed=checks.filter(item=>!item.pass)
const pkg=JSON.parse(read('package.json'))
const label=`V${pkg.version.replace(/\.0$/,'').replaceAll('.','-')}`
const report={version:pkg.version,generatedAt:new Date().toISOString(),checks:checks.length,passed:checks.length-failed.length,failed:failed.length,results:checks}
fs.writeFileSync(path.join(root,`INTEGRATION-FOUNDATION-AUDIT-${label}.json`),JSON.stringify(report,null,2)+'\n')
console.log(`${report.passed}/${report.checks} verificações da fundação de integrações aprovadas.`)
if(failed.length){for(const item of failed)console.error(`FALHA ${item.id}: ${item.detail}`);process.exit(1)}
