-- RealTalent V100.46.2 — workers segregados por responsabilidade.
-- Configure app.settings.supabase_url, app.settings.integration_worker_secret e app.settings.communication_worker_secret no ambiente protegido.
create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;
select cron.unschedule(jobid) from cron.job where jobname in (
  'realtalent-communication-sync','realtalent-integration-sync','realtalent-google-sync','realtalent-microsoft-sync',
  'realtalent-meta-sync','realtalent-whatsapp-sync','realtalent-token-refresh','realtalent-integration-health','realtalent-integration-maintenance','realtalent-lead-geocoding'
);
select cron.schedule('realtalent-google-sync','* * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-google-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{"limit":25}'::jsonb);$$);
select cron.schedule('realtalent-microsoft-sync','* * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-microsoft-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{"limit":25}'::jsonb);$$);
select cron.schedule('realtalent-meta-sync','*/2 * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-meta-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{"limit":20}'::jsonb);$$);
select cron.schedule('realtalent-whatsapp-sync','*/2 * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-whatsapp-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{"limit":20}'::jsonb);$$);
select cron.schedule('realtalent-token-refresh','*/5 * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-token-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{"limit":30}'::jsonb);$$);
select cron.schedule('realtalent-integration-health','*/15 * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-health-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{"limit":30}'::jsonb);$$);
select cron.schedule('realtalent-integration-maintenance','*/5 * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/integration-maintenance-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.integration_worker_secret')),body:='{}'::jsonb);$$);
select cron.schedule('realtalent-communication-dispatch','* * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/communication-dispatch-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.communication_worker_secret')),body:='{"limit":25}'::jsonb);$$);

select cron.schedule('realtalent-lead-geocoding','* * * * *',$$select net.http_post(url:=current_setting('app.settings.supabase_url')||'/functions/v1/lead-geocode-worker',headers:=jsonb_build_object('content-type','application/json','x-worker-secret',current_setting('app.settings.maps_worker_secret')),body:='{"limit":25}'::jsonb);$$);
