import { useEffect, useMemo, useState } from 'react'
import { BadgeDollarSign, Boxes, CalendarClock, Check, ChevronRight, CircleDollarSign, CopyPlus, FilePenLine, FileText, Plus, ReceiptText, Send, TrendingUp, XCircle } from 'lucide-react'
import { useApp } from '../../app/app-context'
import { Button } from '../../components/ui/button'
import { Modal } from '../../components/ui/modal'
import { StatusPill } from '../../components/ui/status-pill'
import type { ForecastCategory, ProductBillingInterval, ProductBillingType, ProductRecord, ProposalLineItem, ProposalRecord, ProposalStatus, RevenueEntry, RevenueStatus, RevenueType } from '../../domain/types'
import { formatCurrency } from '../../domain/formatters'
import { createId } from '../../lib/id'
import { calculateProposalLine, calculateProposalTotals, calculateRevenueForecast, calculateRevenueSeries } from '../../services/revenue-forecast'

type Tab = 'proposals' | 'products' | 'revenue' | 'forecast'
const proposalStatus: Record<ProposalStatus, { label: string; tone: 'neutral' | 'success' | 'warning' | 'danger' | 'info' }> = {
  draft: { label: 'Rascunho', tone: 'neutral' }, sent: { label: 'Enviada', tone: 'info' }, viewed: { label: 'Visualizada', tone: 'warning' }, accepted: { label: 'Aceita', tone: 'success' }, rejected: { label: 'Recusada', tone: 'danger' }, expired: { label: 'Expirada', tone: 'warning' }, cancelled: { label: 'Cancelada', tone: 'neutral' },
}
const forecastLabels: Record<ForecastCategory, string> = { pipeline: 'Pipeline', best_case: 'Melhor cenário', commit: 'Comprometido', closed: 'Fechado', omitted: 'Fora da previsão' }
const percent = (value: number) => `${Math.round(value)}%`
const dateInput = (date: Date) => { const copy = new Date(date); copy.setMinutes(copy.getMinutes() - copy.getTimezoneOffset()); return copy.toISOString().slice(0, 10) }
const newLine = (product?: ProductRecord): ProposalLineItem => {
  const base = calculateProposalLine({ quantity: 1, unitPrice: product?.unitPrice ?? 0, discountPercent: 0, taxRate: product?.taxRate ?? 0, billingType: product?.billingType ?? 'one_time', billingInterval: product?.billingInterval ?? null })
  return { id: createId('proposal-item'), productId: product?.id ?? null, name: product?.name ?? '', description: product?.description ?? '', quantity: base.quantity, unitPrice: base.unitPrice, discountPercent: base.discountPercent, taxRate: base.taxRate, billingType: product?.billingType ?? 'one_time', billingInterval: product?.billingInterval ?? null, ...base }
}

function ProductModal({ open, product, onClose }: { open: boolean; product: ProductRecord | null; onClose(): void }) {
  const { createProduct, updateProduct } = useApp()
  const [name, setName] = useState(''); const [sku, setSku] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [price, setPrice] = useState('0'); const [billingType, setBillingType] = useState<ProductBillingType>('one_time'); const [interval, setInterval] = useState<ProductBillingInterval>(null); const [taxRate, setTaxRate] = useState('0'); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!open) return; setName(product?.name ?? ''); setSku(product?.sku ?? ''); setDescription(product?.description ?? ''); setCategory(product?.category ?? ''); setPrice(String(product?.unitPrice ?? 0)); setBillingType(product?.billingType ?? 'one_time'); setInterval(product?.billingInterval ?? null); setTaxRate(String(product?.taxRate ?? 0)) }, [open, product])
  const submit = async () => { if (!name.trim()) return; setSaving(true); try { const input = { name, sku, description, category, active: product?.active ?? true, unitPrice: Number(price || 0), billingType, billingInterval: billingType === 'recurring' ? (interval ?? 'month' as const) : null, taxRate: Number(taxRate || 0) }; if (product) await updateProduct(product.id, input); else await createProduct(input); onClose() } finally { setSaving(false) } }
  return <Modal open={open} title={product ? 'Editar produto ou serviço' : 'Novo produto ou serviço'} subtitle="Cadastre preços e recorrência para montar propostas sem digitar tudo novamente." size="lg" onClose={onClose} footer={<><span className="modal__footer-spacer"/><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={() => void submit()}>Salvar</Button></>}>
    <div className="form-grid"><label className="form-field"><span>Nome</span><input value={name} onChange={(e) => setName(e.target.value)} /></label><label className="form-field"><span>SKU</span><input value={sku} onChange={(e) => setSku(e.target.value)} placeholder="Opcional" /></label><label className="form-field form-field--full"><span>Descrição</span><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={3} /></label><label className="form-field"><span>Categoria</span><input value={category} onChange={(e) => setCategory(e.target.value)} /></label><label className="form-field"><span>Preço unitário (R$)</span><input type="number" min="0" step="0.01" value={price} onChange={(e) => setPrice(e.target.value)} /></label><label className="form-field"><span>Cobrança</span><select value={billingType} onChange={(e) => { const next = e.target.value as ProductBillingType; setBillingType(next); setInterval(next === 'recurring' ? 'month' : null) }}><option value="one_time">Única</option><option value="recurring">Recorrente</option></select></label>{billingType === 'recurring' ? <label className="form-field"><span>Periodicidade</span><select value={interval ?? 'month'} onChange={(e) => setInterval(e.target.value as ProductBillingInterval)}><option value="month">Mensal</option><option value="quarter">Trimestral</option><option value="year">Anual</option></select></label> : null}<label className="form-field"><span>Imposto (%)</span><input type="number" min="0" step="0.01" value={taxRate} onChange={(e) => setTaxRate(e.target.value)} /></label></div>
  </Modal>
}

function ProposalModal({ open, proposal, onClose }: { open: boolean; proposal: ProposalRecord | null; onClose(): void }) {
  const { snapshot, createProposal, updateProposal } = useApp(); const leads = useMemo(() => snapshot?.leads.filter((lead) => lead.status === 'active') ?? [], [snapshot]); const products = useMemo(() => snapshot?.products.filter((item) => item.active) ?? [], [snapshot])
  const [leadId, setLeadId] = useState(''); const [title, setTitle] = useState('Proposta comercial'); const [forecastCategory, setForecastCategory] = useState<ForecastCategory>('pipeline'); const [probability, setProbability] = useState('30'); const [validUntil, setValidUntil] = useState(''); const [notes, setNotes] = useState(''); const [terms, setTerms] = useState('Validade sujeita à disponibilidade e aceite formal.'); const [items, setItems] = useState<ProposalLineItem[]>([newLine()]); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!open) return; const limit = new Date(); limit.setDate(limit.getDate() + 15); setLeadId(proposal?.leadId ?? leads[0]?.id ?? ''); setTitle(proposal?.title ?? 'Proposta comercial'); setForecastCategory(proposal?.forecastCategory ?? 'pipeline'); setProbability(String(proposal?.probability ?? 30)); setValidUntil(proposal?.validUntil ?? dateInput(limit)); setNotes(proposal?.notes ?? ''); setTerms(proposal?.terms ?? 'Validade sujeita à disponibilidade e aceite formal.'); setItems(proposal?.items.length ? proposal.items : [newLine()]) }, [open, proposal, leads])
  const totals = useMemo(() => calculateProposalTotals(items), [items])
  const patchLine = (id: string, patch: Partial<ProposalLineItem>) => setItems((current) => current.map((item) => { if (item.id !== id) return item; const next = { ...item, ...patch }; return { ...next, ...calculateProposalLine(next) } }))
  const pickProduct = (lineId: string, productId: string) => { const product = products.find((item) => item.id === productId); if (!product) return; const next = newLine(product); patchLine(lineId, { ...next, id: lineId }) }
  const submit = async () => { if (!leadId || !title.trim() || !items.length || items.some((item) => !item.name.trim())) return; setSaving(true); try { const input = { leadId, opportunityId: snapshot?.leads.find((lead) => lead.id === leadId)?.opportunityId ?? null, companyId: snapshot?.leads.find((lead) => lead.id === leadId)?.companyId ?? null, contactId: snapshot?.leads.find((lead) => lead.id === leadId)?.primaryContactId ?? null, title, status: proposal?.status ?? 'draft' as ProposalStatus, forecastCategory, probability: Number(probability || 0), currency: 'BRL' as const, subtotal: totals.subtotal, discountTotal: totals.discountTotal, taxTotal: totals.taxTotal, total: totals.total, recurringMonthlyTotal: totals.recurringMonthlyTotal, validUntil: validUntil || null, ownerId: snapshot?.leads.find((lead) => lead.id === leadId)?.ownerId ?? null, notes, terms, items }; if (proposal) await updateProposal(proposal.id, input); else await createProposal(input); onClose() } finally { setSaving(false) } }
  return <Modal open={open} size="full" title={proposal ? `Editar ${proposal.proposalNumber} · v${proposal.version}` : 'Nova proposta'} subtitle="Monte itens, recorrência, desconto e previsão em uma única operação." onClose={onClose} footer={<><div className="proposal-modal-totals"><span>Total <strong>{formatCurrency(totals.total)}</strong></span><span>MRR <strong>{formatCurrency(totals.recurringMonthlyTotal)}</strong></span></div><span className="modal__footer-spacer"/><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={() => void submit()}>Salvar proposta</Button></>}>
    <div className="proposal-editor"><section className="proposal-editor__meta"><div className="form-grid"><label className="form-field"><span>Lead</span><select value={leadId} disabled={Boolean(proposal)} onChange={(e) => setLeadId(e.target.value)}><option value="">Selecione</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.name} · {lead.company}</option>)}</select></label><label className="form-field"><span>Título</span><input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="form-field"><span>Categoria de previsão</span><select value={forecastCategory} onChange={(e) => setForecastCategory(e.target.value as ForecastCategory)}>{Object.entries(forecastLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="form-field"><span>Probabilidade</span><input type="number" min="0" max="100" value={probability} onChange={(e) => setProbability(e.target.value)} /></label><label className="form-field"><span>Validade</span><input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} /></label><label className="form-field form-field--full"><span>Observações</span><textarea rows={2} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div></section>
    <section className="proposal-line-items"><header><div><strong>Itens da proposta</strong><small>Valores em reais; a recorrência é convertida para MRR.</small></div><Button size="sm" variant="secondary" onClick={() => setItems((current) => [...current, newLine()])}><Plus size={15}/> Item</Button></header>{items.map((item, index) => <article key={item.id}><div className="proposal-item-grid"><label><span>Produto</span><select value={item.productId ?? ''} onChange={(e) => pickProduct(item.id, e.target.value)}><option value="">Item personalizado</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label className="proposal-item-name"><span>Descrição do item</span><input value={item.name} onChange={(e) => patchLine(item.id, { name: e.target.value })}/></label><label><span>Qtd.</span><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(e) => patchLine(item.id, { quantity: Number(e.target.value) })}/></label><label><span>Preço</span><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(e) => patchLine(item.id, { unitPrice: Number(e.target.value) })}/></label><label><span>Desconto %</span><input type="number" min="0" max="100" value={item.discountPercent} onChange={(e) => patchLine(item.id, { discountPercent: Number(e.target.value) })}/></label><label><span>Cobrança</span><select value={item.billingType} onChange={(e) => patchLine(item.id, { billingType: e.target.value as ProductBillingType, billingInterval: e.target.value === 'recurring' ? 'month' : null })}><option value="one_time">Única</option><option value="recurring">Recorrente</option></select></label><div className="proposal-item-total"><span>Total</span><strong>{formatCurrency(item.lineTotal)}</strong>{item.recurringMonthlyTotal ? <small>{formatCurrency(item.recurringMonthlyTotal)} MRR</small> : null}</div><button type="button" aria-label={`Remover item ${index + 1}`} onClick={() => setItems((current) => current.filter((line) => line.id !== item.id))}><XCircle size={18}/></button></div></article>)}</section>
    <label className="form-field"><span>Termos comerciais</span><textarea rows={4} value={terms} onChange={(e) => setTerms(e.target.value)} /></label></div>
  </Modal>
}

function RevenueModal({ open, onClose }: { open: boolean; onClose(): void }) {
  const { snapshot, createRevenueEntry } = useApp(); const [leadId, setLeadId] = useState(''); const [type, setType] = useState<RevenueType>('one_time'); const [status, setStatus] = useState<RevenueStatus>('recognized'); const [amount, setAmount] = useState('0'); const [mrr, setMrr] = useState('0'); const [recognizedAt, setRecognizedAt] = useState(dateInput(new Date())); const [description, setDescription] = useState('Receita manual'); const [saving, setSaving] = useState(false)
  const submit = async () => { setSaving(true); try { const lead = snapshot?.leads.find((item) => item.id === leadId); await createRevenueEntry({ proposalId: null, leadId: leadId || null, opportunityId: lead?.opportunityId ?? null, revenueType: type, status, amount: Number(amount || 0), recurringMonthlyAmount: type === 'recurring' ? Number(mrr || 0) : 0, recognizedAt: new Date(`${recognizedAt}T12:00:00`).toISOString(), description, ownerId: lead?.ownerId ?? null }); onClose() } finally { setSaving(false) } }
  return <Modal open={open} title="Registrar receita" subtitle="Use para ajustes ou receitas que não nasceram de uma proposta." onClose={onClose} footer={<><span className="modal__footer-spacer"/><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={() => void submit()}>Registrar</Button></>}><div className="form-grid"><label className="form-field form-field--full"><span>Lead relacionado</span><select value={leadId} onChange={(e) => setLeadId(e.target.value)}><option value="">Sem lead</option>{snapshot?.leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.name} · {lead.company}</option>)}</select></label><label className="form-field"><span>Tipo</span><select value={type} onChange={(e) => setType(e.target.value as RevenueType)}><option value="one_time">Única</option><option value="recurring">Recorrente</option></select></label><label className="form-field"><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value as RevenueStatus)}><option value="recognized">Reconhecida</option><option value="forecast">Prevista</option><option value="cancelled">Cancelada</option></select></label><label className="form-field"><span>Valor único</span><input type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)}/></label>{type === 'recurring' ? <label className="form-field"><span>MRR</span><input type="number" min="0" step="0.01" value={mrr} onChange={(e) => setMrr(e.target.value)}/></label> : null}<label className="form-field"><span>Data</span><input type="date" value={recognizedAt} onChange={(e) => setRecognizedAt(e.target.value)}/></label><label className="form-field form-field--full"><span>Descrição</span><input value={description} onChange={(e) => setDescription(e.target.value)}/></label></div></Modal>
}

export function ProposalsPage() {
  const { snapshot, canWrite, updateProduct, deleteProduct, updateProposalStatus, createProposalRevision, deleteProposal, updateRevenueEntryStatus } = useApp(); const [tab, setTab] = useState<Tab>('proposals'); const [productModal, setProductModal] = useState(false); const [editingProduct, setEditingProduct] = useState<ProductRecord | null>(null); const [proposalModal, setProposalModal] = useState(false); const [editingProposal, setEditingProposal] = useState<ProposalRecord | null>(null); const [revenueModal, setRevenueModal] = useState(false); const [query, setQuery] = useState('')
  const forecast = useMemo(() => snapshot ? calculateRevenueForecast(snapshot) : null, [snapshot]); const series = useMemo(() => snapshot ? calculateRevenueSeries(snapshot) : [], [snapshot]); const maxSeries = Math.max(1, ...series.flatMap((item) => [item.recognized, item.forecast]))
  if (!snapshot || !forecast) return null
  const proposals = snapshot.proposals.filter((proposal) => { const lead = snapshot.leads.find((item) => item.id === proposal.leadId); return `${proposal.proposalNumber} ${proposal.title} ${lead?.name ?? ''} ${lead?.company ?? ''}`.toLowerCase().includes(query.toLowerCase()) })
  const leadName = (id: string) => { const lead = snapshot.leads.find((item) => item.id === id); return lead ? `${lead.name} · ${lead.company}` : 'Lead removido' }
  const statusAction = async (proposal: ProposalRecord, status: ProposalStatus) => { if (!canWrite) return; await updateProposalStatus(proposal.id, status) }
  return <div className="page-stack proposals-page"><section className="panel proposals-hero"><div><span className="eyebrow">Receita comercial</span><h2>Propostas, produtos e previsão</h2><p>Controle versões, aceite, receita única, MRR e forecast ponderado.</p></div><Button onClick={() => { setEditingProposal(null); setProposalModal(true) }} disabled={!canWrite}><Plus size={17}/> Nova proposta</Button></section>
    <section className="proposal-kpis"><article><span><FileText/></span><small>Pipeline em propostas</small><strong>{formatCurrency(forecast.pipelineTotal)}</strong><em>{forecast.proposals.length} proposta(s) no mês</em></article><article><span><TrendingUp/></span><small>Forecast ponderado</small><strong>{formatCurrency(forecast.weightedForecast)}</strong><em>probabilidade por proposta</em></article><article><span><CircleDollarSign/></span><small>Receita reconhecida</small><strong>{formatCurrency(forecast.closedRevenue)}</strong><em>mês atual</em></article><article><span><BadgeDollarSign/></span><small>MRR ativo + previsto</small><strong>{formatCurrency(forecast.activeMrrForecast)}</strong><em>{formatCurrency(forecast.recognizedMrr)} reconhecido</em></article></section>
    <nav className="proposal-tabs" aria-label="Áreas de propostas">{([{ id: 'proposals', label: 'Propostas', icon: FileText }, { id: 'products', label: 'Produtos', icon: Boxes }, { id: 'revenue', label: 'Receita', icon: ReceiptText }, { id: 'forecast', label: 'Forecast', icon: TrendingUp }] as const).map(({ id, label, icon: Icon }) => <button key={id} type="button" className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}><Icon size={16}/>{label}</button>)}</nav>
    {tab === 'proposals' ? <section className="panel"><div className="panel__heading"><div><span className="eyebrow">Controle comercial</span><h3>Propostas e revisões</h3></div><input className="proposal-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar proposta ou lead" /></div><div className="proposal-list">{proposals.map((proposal) => <article key={proposal.id}><div className="proposal-list__main"><div><span>{proposal.proposalNumber} · v{proposal.version}</span><strong>{proposal.title}</strong><small>{leadName(proposal.leadId)}</small></div><StatusPill tone={proposalStatus[proposal.status].tone}>{proposalStatus[proposal.status].label}</StatusPill></div><div className="proposal-list__forecast"><span>{forecastLabels[proposal.forecastCategory]}</span><strong>{percent(proposal.probability)}</strong></div><div className="proposal-list__money"><strong>{formatCurrency(proposal.total)}</strong><small>{proposal.recurringMonthlyTotal ? `${formatCurrency(proposal.recurringMonthlyTotal)} MRR` : 'sem recorrência'}</small></div><div className="proposal-list__actions"><button type="button" title="Editar" disabled={!canWrite || proposal.status === 'accepted'} onClick={() => { setEditingProposal(proposal); setProposalModal(true) }}><FilePenLine size={16}/></button>{proposal.status === 'draft' ? <button type="button" title="Enviar" disabled={!canWrite} onClick={() => void statusAction(proposal, 'sent')}><Send size={16}/></button> : null}{['sent','viewed'].includes(proposal.status) ? <button type="button" title="Aceitar" disabled={!canWrite} onClick={() => void statusAction(proposal, 'accepted')}><Check size={16}/></button> : null}{['sent','viewed'].includes(proposal.status) ? <button type="button" title="Recusar" disabled={!canWrite} onClick={() => void statusAction(proposal, 'rejected')}><XCircle size={16}/></button> : null}<button type="button" title="Nova revisão" disabled={!canWrite} onClick={() => void createProposalRevision(proposal.id)}><CopyPlus size={16}/></button><button type="button" title="Excluir" disabled={!canWrite || proposal.status === 'accepted'} onClick={() => void deleteProposal(proposal.id)}><span>×</span></button></div></article>)}{!proposals.length ? <div className="empty-state"><FileText/><strong>Nenhuma proposta encontrada</strong><p>Crie uma proposta a partir dos leads ativos.</p></div> : null}</div></section> : null}
    {tab === 'products' ? <section className="panel"><div className="panel__heading"><div><span className="eyebrow">Catálogo</span><h3>Produtos e serviços</h3></div><Button size="sm" onClick={() => { setEditingProduct(null); setProductModal(true) }} disabled={!canWrite}><Plus size={15}/> Novo item</Button></div><div className="product-grid">{snapshot.products.map((product) => <article key={product.id}><div><span>{product.category || 'Sem categoria'}</span><strong>{product.name}</strong><small>{product.sku || 'Sem SKU'}</small></div><div><strong>{formatCurrency(product.unitPrice)}</strong><small>{product.billingType === 'recurring' ? `recorrente · ${product.billingInterval === 'year' ? 'anual' : product.billingInterval === 'quarter' ? 'trimestral' : 'mensal'}` : 'pagamento único'}</small></div><StatusPill tone={product.active ? 'success' : 'neutral'}>{product.active ? 'Ativo' : 'Inativo'}</StatusPill><div><button type="button" onClick={() => { setEditingProduct(product); setProductModal(true) }}><FilePenLine size={16}/></button><button type="button" onClick={() => void updateProduct(product.id, { active: !product.active })}>{product.active ? 'Pausar' : 'Ativar'}</button><button type="button" onClick={() => void deleteProduct(product.id)}>Excluir</button></div></article>)}</div></section> : null}
    {tab === 'revenue' ? <section className="panel"><div className="panel__heading"><div><span className="eyebrow">Reconhecimento</span><h3>Receitas e recorrência</h3></div><Button size="sm" onClick={() => setRevenueModal(true)} disabled={!canWrite}><Plus size={15}/> Registrar receita</Button></div><div className="revenue-list">{snapshot.revenueEntries.map((entry) => <article key={entry.id}><span className={`revenue-icon revenue-icon--${entry.revenueType}`}>{entry.revenueType === 'recurring' ? <CalendarClock/> : <CircleDollarSign/>}</span><div><strong>{entry.description}</strong><small>{new Date(entry.recognizedAt).toLocaleDateString('pt-BR')} · {entry.proposalId ? 'gerada por proposta' : 'lançamento manual'}</small></div><div><strong>{formatCurrency(entry.amount)}</strong>{entry.recurringMonthlyAmount ? <small>{formatCurrency(entry.recurringMonthlyAmount)} MRR</small> : null}</div><StatusPill tone={entry.status === 'recognized' ? 'success' : entry.status === 'forecast' ? 'info' : 'neutral'}>{entry.status === 'recognized' ? 'Reconhecida' : entry.status === 'forecast' ? 'Prevista' : 'Cancelada'}</StatusPill><button type="button" disabled={!canWrite} onClick={() => void updateRevenueEntryStatus(entry.id, entry.status === 'cancelled' ? 'recognized' : 'cancelled')}>{entry.status === 'cancelled' ? 'Reativar' : 'Cancelar'}</button></article>)}</div></section> : null}
    {tab === 'forecast' ? <><section className="forecast-categories">{forecast.byCategory.filter((item) => item.category !== 'omitted').map((item) => <article key={item.category}><span>{forecastLabels[item.category]}</span><strong>{formatCurrency(item.value)}</strong><small>{formatCurrency(item.weightedValue)} ponderado · {item.proposals} proposta(s)</small><div><i style={{ width: `${forecast.pipelineTotal ? Math.min(100, item.value / forecast.pipelineTotal * 100) : 0}%` }}/></div></article>)}</section><section className="panel"><div className="panel__heading"><div><span className="eyebrow">Horizonte de receita</span><h3>Realizado e previsto</h3></div><StatusPill tone="info">Melhor cenário {formatCurrency(forecast.bestCaseForecast)}</StatusPill></div><div className="revenue-series">{series.map((item) => <article key={item.month}><span>{item.month}</span><div><i className="is-recognized" style={{ height: `${Math.max(4, item.recognized / maxSeries * 100)}%` }} title={`Reconhecido ${formatCurrency(item.recognized)}`}/><i className="is-forecast" style={{ height: `${Math.max(4, item.forecast / maxSeries * 100)}%` }} title={`Previsto ${formatCurrency(item.forecast)}`}/></div><small>{formatCurrency(item.recognized + item.forecast)}</small></article>)}</div><div className="forecast-summary"><div><span>Comprometido</span><strong>{formatCurrency(forecast.commitForecast)}</strong></div><ChevronRight/><div><span>Ponderado</span><strong>{formatCurrency(forecast.weightedForecast)}</strong></div><ChevronRight/><div><span>Melhor cenário</span><strong>{formatCurrency(forecast.bestCaseForecast)}</strong></div></div></section></> : null}
    <ProductModal open={productModal} product={editingProduct} onClose={() => setProductModal(false)}/><ProposalModal open={proposalModal} proposal={editingProposal} onClose={() => setProposalModal(false)}/><RevenueModal open={revenueModal} onClose={() => setRevenueModal(false)}/>
  </div>
}
